routes/web.php
<?php

use App\Http\Controllers\Admin\{
    UserController,
    ProductController,
    CategoryController,
    DashboardController
};
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
    Route::any('users/search', [UserController::class, 'search'])->name('users.search');
    Route::resource('users', UserController::class)->names('users');

    Route::any('products/search', [ProductController::class, 'search'])->name('products.search');
    Route::resource('products', ProductController::class)->names('products');

    Route::any('/categories/search', [CategoryController::class, 'search'])->name('categories.search');
    Route::resource('/categories', CategoryController::class)->names('categories');

    Route::get('/', [DashboardController::class, 'index'])->name('admin');
});

Auth::routes(['register' => false]);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Product.php
<?php

namespace App\Models;

use App\Http\Controllers\Admin\CategoryController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use \Illuminate\Database\Eloquent\Builder;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'name',
        'url',
        'price',
        'description'
    ];

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope('orderByPrice', function (Builder $builder){
            $builder->orderBy('price', 'DESC');
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUpdateProductFormRequest;
use App\Repositories\Contracts\ProductRepositoryInterface;


class ProductController extends Controller
{
    protected $product;

    public function __construct(ProductRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->repository
                        ->relationships('category')
                        ->orderBy('id', 'DESC')
                        ->paginate();

        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUpdateProductFormRequest $request)
    {
        //$category = Category::find($request->category_id);
        //$product  = $category->products()->create($request->all());

        $product = $this->repository->store($request->all());

        return redirect()
                    ->route('products.index')
                    ->with('success', 'Produto cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!$product = $this->repository->with('category')->find($id))
            return redirect()->back();

        return view('admin.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!$product = $this->repository->find($id))
            return redirect()->back();

        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUpdateProductFormRequest $request, $id)
    {
        if(!$product = $this->repository->find($id))
            return redirect()->back();

        $product->update($request->all());

        return redirect()
            ->route('products.index')
            ->with('success', 'Produto atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!$product = $this->repository->find($id))
            return redirect()->back();

        $product->delete();

        return redirect()
            ->route('products.index')
            ->with('success', 'Produto deletado com sucesso!');
    }

    public function search(Request $request)
    {
        $filters = $request->except('_token');

        $products = $this->repository->search($filters);

        return view('admin.products.index', compact('products', 'filters'));
    }
}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Novo Produto')

@section('content_header')
    <h1>Novo Produto</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Produtos</a></li>
        <li class="breadcrumb-item active">Novo Produto</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            @include('admin.includes.alerts')
                            {{ Form::open(['route' => 'products.store']) }}
                                @include('admin.products.partials.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', "Editar Produto: {$product->title}")

@section('content_header')
    <h1>Editar Produto: {{$product->title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Produtos</a></li>
        <li class="breadcrumb-item active">Editar Produto</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            @include('admin.includes.alerts')
                            <!--<form action="{{ route('products.update', $product->id) }}" method="post">
                                @method('PUT')
                                @include('admin.products.partials.form')
                            </form>-->
                            {{ Form::model($product, ['route' => ['products.update', $product->id]]) }}
                                @include('admin.products.partials.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Listagem de Produtos')

@section('content_header')
    <h1>Produtos</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item active">Produtos</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('products.create') }}" class="btn btn-success">Novo Produto</a>
                            <hr>
                                {{ Form::open(['route' => 'products.search', 'class' => 'form-inline' ]) }}
                                    {{ Form::text('name', request()->name, ['placeholder' => 'Nome', 'class' => 'form-control']) }}
                                    {{ Form::text('price', request()->price, ['placeholder' => 'Preço', 'class' => 'form-control ml-1']) }}
                                    {{ Form::text('description', request()->description, ['placeholder' => 'Descrição', 'class' => 'form-control ml-1']) }}
                                    {{ Form::select('category_id', $categories, request()->category_id, ['placeholder' => 'Selecione uma categoria', 'class' => 'form-control ml-1']) }}
                                    {{ Form::submit('Pesquisar', ['class' => 'btn btn-primary ml-1']) }}
                                    <a href="{{ route('products.index') }}" class="btn btn-danger ml-1">Limpar</a>
                                {{ Form::close() }}
                            <hr>
                            @include('admin.includes.alerts')
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th scope="row">Título</th>
                                    <th scope="row">Categoria</th>
                                    <th scope="row">Preço</th>
                                    <th scope="row" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($products as $product)
                                    <tr>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->category->title }}</td>
                                        <td>R$ {{ $product->price }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('products.edit', $product->id) }}"
                                               class="btn btn-sm btn-warning">Editar</a>
                                            <a href="{{ route('products.show', $product->id) }}"
                                               class="btn btn-sm btn-primary">Detalhes</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="card-footer clearfix">
                            @if(isset($filters))
                                {!! $products->appends($filters)->links('vendor.pagination.bootstrap-5') !!}
                            @else
                                {!! $products->links('vendor.pagination.bootstrap-5') !!}
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/products/show.blade.php
@extends('adminlte::page')

@section('title', "Detalhes do Produto: {$product->title}")

@section('content_header')
    <h1>Detalhes do Produto: {{$product->title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Produtos</a></li>
        <li class="breadcrumb-item active">Detalhes do Produto</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <p>
                                <strong>ID:</strong> {{ $product->id }}
                            </p>
                            <p>
                                <strong>Título:</strong> {{ $product->name }}
                            </p>
                            <p>
                                <strong>URL:</strong> {{ $product->url }}
                            </p>
                            <p>
                                <strong>Categoria:</strong> {{ $product->category->title }}
                            </p>
                            <p>
                                <strong>Descrição:</strong><br>
                                {{ $product->description }}
                            </p>
                            <hr>
                                {{ Form::open(['route' => ['products.destroy', $product->id], 'method' => 'delete']) }}
                                    {{ Form::submit('Deletar', ['class' => 'btn btn-sm btn-danger']) }}
                                {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop