routes/web.php
<?php

use App\Http\Controllers\Admin\{
    UserController,
    ProductController,
    CategoryController,
    DashboardController
};
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
    Route::any('users/search', [UserController::class, 'search'])->name('users.search');
    Route::resource('users', UserController::class)->names('users');

    Route::any('products/search', [ProductController::class, 'search'])->name('products.search');
    Route::resource('products', ProductController::class)->names('products');

    Route::any('/categories/search', [CategoryController::class, 'search'])->name('categories.search');
    Route::resource('/categories', CategoryController::class)->names('categories');

    Route::get('/', [DashboardController::class, 'index'])->name('admin');
});

Auth::routes(['register' => false]);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUpdateCategoryFormRequest;
use App\Repositories\Contracts\CategoryRepositoryInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $repository;

    public function __construct(CategoryRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->repository
                        ->orderBy('id', 'DESC')
                        ->paginate();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\StoreUpdateCategoryFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUpdateCategoryFormRequest $request)
    {
        $this->repository->store([
            'title' => $request->title,
            'description' => $request->description,
        ]);

        return redirect()
                    ->route('categories.index')
                    ->with('success', 'Cadastro realizado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->repository->findWhereFirst('id', $id);

        if(!$category)
            return redirect()->back();

        return view('admin.categories.show', compact("category"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->repository->where('id', $id)->first();

        if(!$category)
            return redirect()->back();

        return view('admin.categories.edit', compact("category"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUpdateCategoryFormRequest $request, $id)
    {
        $this->repository
                ->update($id, [
                    'title' => $request->title,
                    'url' => $request->url,
                    'description' => $request->description
                ]);

        return redirect()
                    ->route('categories.index')
                    ->with('success', 'Cadastro atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->repository->findWhereFirst('id', $id);
        $products = $this->repository->productsByCategoryId($id);

        if(count($products)>0)
            return redirect()
                ->route('categories.index')
                ->with('danger', 'Categoria não pode ser deletada!');

        if(!$category)
            return redirect()->back();

        $this->repository->delete($id);

        return redirect()
                    ->route('categories.index')
                    ->with('success', 'Categoria deletada com sucesso!');
    }

    public function search(Request $request)
    {
        $data = $request->except('_token');

        $categories = $this->repository->search($data);

        return view('admin.categories.index', compact(['categories', 'data']));
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'Nova Categoria')

@section('content_header')
    <h1>Nova Categoria</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorias</a></li>
        <li class="breadcrumb-item active">Nova Categoria</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            @include('admin.includes.alerts')
                            <form action="{{ route('categories.store') }}" method="post">
                                @csrf
                                @include('admin.categories.partials.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title', "Editar Categoria: {$category->title}")

@section('content_header')
    <h1>Editar Categoria: {{$category->title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorias</a></li>
        <li class="breadcrumb-item active">Editar Categoria</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            @include('admin.includes.alerts')
                            <form action="{{ route('categories.update', $category->id) }}" method="post">
                                @method('PUT')
                                @include('admin.categories.partials.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Listagem de Categorias')

@section('content_header')
    <h1>Categorias</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item active">Categorias</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('categories.create') }}" class="btn btn-success">Nova Categoria</a>
                            <hr>
                            <form action="{{ route('categories.search') }}" method="post" class="form form-inline">
                                @csrf
                                <input type="text" name="title" id="title" class="form-control mr-1"
                                       value="{{ request()->title }}" placeholder="Título">
                                <input type="text" name="url" id="url" class="form-control mr-1"
                                       value="{{ request()->url }}" placeholder="URL">
                                <input type="text" name="description" id="description" class="form-control mr-1"
                                       value="{{ request()->description }}" placeholder="Descrição">
                                <button type="submit" class="btn btn-primary mr-1">Pesquisar</button>
                                <a href="{{ route('categories.index') }}" class="btn btn-danger">Limpar</a>
                            </form>
                            <hr>
                            @if(request()->search)
                                <p>Resultados para a pesquisa: <strong>{{ request()->search }}</strong></p>
                            @endif
                            @include('admin.includes.alerts')
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th scope="row">#</th>
                                    <th scope="row">Título</th>
                                    <th scope="row">URL</th>
                                    <th scope="row" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr>
                                        <td>{{ $category->id }}</td>
                                        <td>{{ $category->title }}</td>
                                        <td>{{ $category->url }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('categories.edit', $category->id) }}"
                                               class="btn btn-sm btn-warning">Editar</a>
                                            <a href="{{ route('categories.show', $category->id) }}"
                                               class="btn btn-sm btn-primary">Detalhes</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="card-footer clearfix">
                            @if(isset($data))
                                {!! $categories->appends($data)->links('vendor.pagination.bootstrap-5') !!}
                            @else
                                {!! $categories->links('vendor.pagination.bootstrap-5') !!}
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', "Detalhes da Categoria: {$category->title}")

@section('content_header')
    <h1>Detalhes da Categoria: {{$category->title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorias</a></li>
        <li class="breadcrumb-item active">Detalhes da Categoria</li>
    </ol>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <p>
                                <strong>ID:</strong> {{ $category->id }}
                            </p>
                            <p>
                                <strong>Título:</strong> {{ $category->title }}
                            </p>
                            <p>
                                <strong>URL:</strong> {{ $category->url }}
                            </p>
                            <p>
                                <strong>Descrição:</strong><br>
                                {{ $category->description }}
                            </p>
                            <hr>
                            <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger">Deletar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop